# @generated by metaobjects (metagen:capture_contract) from the model in metaobjects/.
# Do not edit: change the metadata and regenerate. A hand edit fails
# `metaobjects verify --codegen`.
"""What the model declares, held to a committed capture of a real server.

It fails in one direction: an attribute that is declared, is in no captured
answer, and carries no reason it could not be observed. That is an invented
name, and whatever reads it is empty on every real server. The other direction
is reported and never failed: a server sends far more than a tool reads, and
the model declares what is read.

Run this file to print both directions. The standard library is all it needs.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

#: The committed capture, as a path from the project root.
CAPTURE_FILE = "tests/fixtures/ha-shape/capture.json"

#: Each declared object: the captured answers that show it, its attributes, and
#: the reason for any that no capture could have seen.
DECLARED = {
    "homeassistant::core::State": {
        "key": "state",
        "capture": ("state",),
        "fields": (
            "entity_id",
            "state",
            "attributes",
            "last_changed",
            "last_reported",
            "last_updated",
            "context",
        ),
        "unobserved": {},
    },
    "homeassistant::core::StateAttributes": {
        "key": "state_attributes",
        "capture": ("state.attributes",),
        "fields": (
            "friendly_name",
            "device_class",
            "state_class",
            "unit_of_measurement",
            "supported_features",
            "brightness",
            "temperature",
            "battery_level",
        ),
        "unobserved": {
            "battery_level": "set by integrations for battery-powered devices; no demo entity in the lab publishes it",
        },
    },
    "homeassistant::core::Context": {
        "key": "context",
        "capture": ("state.context",),
        "fields": (
            "id",
            "parent_id",
            "user_id",
        ),
        "unobserved": {},
    },
    "homeassistant::core::ApiRoot": {
        "key": "api_root",
        "capture": ("rest.api_root",),
        "fields": ("message",),
        "unobserved": {},
    },
    "homeassistant::core::Config": {
        "key": "config",
        "capture": ("rest.config",),
        "fields": (
            "version",
            "location_name",
        ),
        "unobserved": {},
    },
    "homeassistant::core::RestError": {
        "key": "rest_error",
        "capture": ("rest.error",),
        "fields": ("message",),
        "unobserved": {},
    },
    "homeassistant::logbook::LogbookEntry": {
        "key": "logbook_entry",
        "capture": ("logbook.row",),
        "fields": (
            "when",
            "name",
            "entity_id",
            "domain",
            "state",
            "message",
            "source",
            "context_id",
            "context_user_id",
            "context_event_type",
            "context_domain",
            "context_service",
            "context_entity_id",
            "context_entity_id_name",
            "context_name",
            "context_message",
            "context_source",
        ),
        "unobserved": {},
    },
    "homeassistant::recorder::StatisticMeta": {
        "key": "statistic_meta",
        "capture": ("recorder.statistic_meta",),
        "fields": (
            "statistic_id",
            "name",
            "source",
            "has_sum",
            "has_mean",
            "mean_type",
            "display_unit_of_measurement",
            "statistics_unit_of_measurement",
            "unit_class",
        ),
        "unobserved": {},
    },
    "homeassistant::recorder::StatisticsRow": {
        "key": "statistics_row",
        "capture": ("recorder.statistics_row",),
        "fields": (
            "start",
            "end",
            "change",
            "state",
            "sum",
            "mean",
            "min",
            "max",
            "last_reset",
        ),
        "unobserved": {},
    },
    "homeassistant::recorder::HistoryState": {
        "key": "history_state",
        "capture": (
            "history.first_row",
            "history.later_row",
        ),
        "fields": (
            "state",
            "last_changed",
            "entity_id",
            "attributes",
            "last_updated",
        ),
        "unobserved": {},
    },
    "homeassistant::registry::EntityEntry": {
        "key": "entity_entry",
        "capture": (
            "registry.entity",
            "registry.entity.extended",
        ),
        "fields": (
            "entity_id",
            "id",
            "unique_id",
            "platform",
            "name",
            "original_name",
            "has_entity_name",
            "area_id",
            "device_id",
            "disabled_by",
            "hidden_by",
            "entity_category",
            "icon",
            "translation_key",
            "config_entry_id",
            "config_subentry_id",
            "categories",
            "options",
            "labels",
            "created_at",
            "modified_at",
            "aliases",
            "capabilities",
            "device_class",
            "original_device_class",
            "original_icon",
        ),
        "unobserved": {},
    },
    "homeassistant::registry::DeviceEntry": {
        "key": "device_entry",
        "capture": ("registry.device",),
        "fields": (
            "id",
            "name",
            "name_by_user",
            "area_id",
            "manufacturer",
            "model",
            "disabled_by",
            "labels",
        ),
        "unobserved": {},
    },
    "homeassistant::registry::AreaEntry": {
        "key": "area_entry",
        "capture": ("registry.area",),
        "fields": (
            "area_id",
            "name",
            "aliases",
            "floor_id",
            "icon",
        ),
        "unobserved": {},
    },
    "homeassistant::registry::FloorEntry": {
        "key": "floor_entry",
        "capture": ("registry.floor",),
        "fields": (
            "floor_id",
            "name",
            "aliases",
            "icon",
            "level",
            "created_at",
            "modified_at",
        ),
        "unobserved": {},
    },
    "homeassistant::registry::EntityUpdateResult": {
        "key": "entity_update_result",
        "capture": ("websocket.entity_update",),
        "fields": (
            "entity_entry",
            "reload_delay",
        ),
        "unobserved": {
            "reload_delay": "sent only when an update enables a disabled entity, and the capture's one update enables none",
        },
    },
    "homeassistant::services::ServiceDomain": {
        "key": "service_domain",
        "capture": ("service.domain",),
        "fields": (
            "domain",
            "services",
        ),
        "unobserved": {},
    },
    "homeassistant::services::Service": {
        "key": "service",
        "capture": ("service",),
        "fields": (
            "name",
            "description",
            "fields",
            "target",
            "response",
        ),
        "unobserved": {},
    },
    "homeassistant::services::ServiceField": {
        "key": "service_field",
        "capture": ("service.field",),
        "fields": (
            "description",
            "required",
            "example",
            "selector",
            "filter",
            "fields",
            "collapsed",
        ),
        "unobserved": {},
    },
    "homeassistant::services::ServiceFieldFilter": {
        "key": "service_field_filter",
        "capture": ("service.field.filter",),
        "fields": ("supported_features",),
        "unobserved": {},
    },
    "homeassistant::services::Selector": {
        "key": "selector",
        "capture": ("service.field.selector",),
        "fields": (
            "select",
            "datetime",
            "number",
            "text",
        ),
        "unobserved": {},
    },
    "homeassistant::services::SelectSelector": {
        "key": "select_selector",
        "capture": ("service.field.selector.select",),
        "fields": ("options",),
        "unobserved": {},
    },
    "homeassistant::services::ServiceResponse": {
        "key": "service_response",
        "capture": ("service.response",),
        "fields": ("optional",),
        "unobserved": {},
    },
    "homeassistant::services::ServiceTarget": {
        "key": "service_target",
        "capture": ("service.target",),
        "fields": (
            "entity",
            "device",
        ),
        "unobserved": {
            "device": "published by a service whose target filters devices, and no integration the lab loads declares one",
        },
    },
    "homeassistant::services::ServiceTargetEntity": {
        "key": "service_target_entity",
        "capture": ("service.target.entity",),
        "fields": (
            "domain",
            "supported_features",
        ),
        "unobserved": {},
    },
    "homeassistant::services::ServiceCallResult": {
        "key": "service_call_result",
        "capture": ("service.call",),
        "fields": (
            "changed_states",
            "service_response",
        ),
        "unobserved": {},
    },
    "homeassistant::websocket::AuthRequired": {
        "key": "auth_required",
        "capture": ("websocket.auth_required",),
        "fields": (
            "type",
            "ha_version",
        ),
        "unobserved": {},
    },
    "homeassistant::websocket::AuthOk": {
        "key": "auth_ok",
        "capture": ("websocket.auth_ok",),
        "fields": (
            "type",
            "ha_version",
        ),
        "unobserved": {},
    },
    "homeassistant::websocket::AuthInvalid": {
        "key": "auth_invalid",
        "capture": ("websocket.auth_invalid",),
        "fields": (
            "type",
            "message",
        ),
        "unobserved": {},
    },
    "homeassistant::websocket::ResultMessage": {
        "key": "result_message",
        "capture": ("websocket.result",),
        "fields": (
            "id",
            "type",
            "success",
            "result",
        ),
        "unobserved": {},
    },
    "homeassistant::websocket::ErrorMessage": {
        "key": "error_message",
        "capture": ("websocket.error",),
        "fields": (
            "id",
            "type",
            "success",
            "error",
        ),
        "unobserved": {},
    },
    "homeassistant::websocket::ErrorDetail": {
        "key": "error_detail",
        "capture": ("websocket.error.error",),
        "fields": (
            "code",
            "message",
        ),
        "unobserved": {},
    },
}

#: Each row: the object it is read from, the answers it is built from, the
#: attributes it reads of that object, and those it reads of any other.
ROWS = {
    "state": {
        "of": "homeassistant::core::State",
        "capture": ("state",),
        "reads": (
            "attributes",
            "entity_id",
            "last_changed",
            "last_reported",
            "last_updated",
            "state",
        ),
        "also": {
            "homeassistant::core::StateAttributes": ("friendly_name",),
        },
    },
    "entity": {
        "of": "homeassistant::registry::EntityEntry",
        "capture": (
            "registry.entity",
            "registry.entity.extended",
        ),
        "reads": (
            "area_id",
            "device_id",
            "disabled_by",
            "entity_category",
            "entity_id",
            "hidden_by",
            "name",
            "original_name",
            "platform",
        ),
        "also": {
            "homeassistant::registry::AreaEntry": (
                "area_id",
                "name",
            ),
            "homeassistant::registry::DeviceEntry": (
                "area_id",
                "id",
                "name",
                "name_by_user",
            ),
        },
    },
    "device": {
        "of": "homeassistant::registry::DeviceEntry",
        "capture": ("registry.device",),
        "reads": (
            "area_id",
            "id",
            "manufacturer",
            "model",
            "name",
            "name_by_user",
        ),
        "also": {
            "homeassistant::registry::AreaEntry": (
                "area_id",
                "name",
            ),
            "homeassistant::registry::EntityEntry": ("device_id",),
        },
    },
    "area": {
        "of": "homeassistant::registry::AreaEntry",
        "capture": ("registry.area",),
        "reads": (
            "area_id",
            "floor_id",
            "name",
        ),
        "also": {
            "homeassistant::registry::DeviceEntry": (
                "area_id",
                "id",
            ),
            "homeassistant::registry::EntityEntry": (
                "area_id",
                "device_id",
            ),
        },
    },
    "logbook": {
        "of": "homeassistant::logbook::LogbookEntry",
        "capture": ("logbook.row",),
        "reads": (
            "context_domain",
            "context_entity_id",
            "context_entity_id_name",
            "context_event_type",
            "context_name",
            "context_service",
            "context_user_id",
            "domain",
            "entity_id",
            "message",
            "name",
            "state",
            "when",
        ),
        "also": {},
    },
    "statistic": {
        "of": "homeassistant::recorder::StatisticMeta",
        "capture": ("recorder.statistic_meta",),
        "reads": (
            "display_unit_of_measurement",
            "has_mean",
            "has_sum",
            "mean_type",
            "name",
            "source",
            "statistic_id",
            "statistics_unit_of_measurement",
            "unit_class",
        ),
        "also": {
            "homeassistant::core::State": (
                "attributes",
                "entity_id",
            ),
            "homeassistant::core::StateAttributes": ("friendly_name",),
        },
    },
    "service_domain": {
        "of": "homeassistant::services::ServiceDomain",
        "capture": ("service.domain",),
        "reads": (
            "domain",
            "services",
        ),
        "also": {},
    },
    "sensor": {
        "of": "homeassistant::core::State",
        "capture": ("state",),
        "reads": (
            "attributes",
            "entity_id",
            "last_reported",
            "last_updated",
            "state",
        ),
        "also": {
            "homeassistant::core::StateAttributes": (
                "device_class",
                "friendly_name",
                "state_class",
                "unit_of_measurement",
            ),
            "homeassistant::registry::AreaEntry": (
                "area_id",
                "name",
            ),
            "homeassistant::registry::DeviceEntry": (
                "area_id",
                "id",
                "name",
                "name_by_user",
            ),
            "homeassistant::registry::EntityEntry": (
                "area_id",
                "device_id",
                "entity_category",
                "entity_id",
                "name",
                "original_name",
            ),
        },
    },
    "service": {
        "of": "homeassistant::services::Service",
        "capture": ("service",),
        "reads": (
            "fields",
            "name",
            "response",
            "target",
        ),
        "also": {
            "homeassistant::services::ServiceDomain": (
                "domain",
                "services",
            ),
            "homeassistant::services::ServiceField": ("fields",),
            "homeassistant::services::ServiceResponse": ("optional",),
        },
    },
    "service_field": {
        "of": "homeassistant::services::ServiceField",
        "capture": ("service.field",),
        "reads": (
            "description",
            "example",
            "fields",
            "required",
            "selector",
        ),
        "also": {
            "homeassistant::services::SelectSelector": ("options",),
            "homeassistant::services::Selector": ("select",),
            "homeassistant::services::Service": ("fields",),
        },
    },
}


def _capture() -> Path:
    """The capture, found from here: this file may be generated into any directory."""
    for parent in Path(__file__).resolve().parents:
        if (parent / CAPTURE_FILE).is_file():
            return parent / CAPTURE_FILE
    raise FileNotFoundError(f"no {CAPTURE_FILE} above {__file__}")


#: Why an attribute could not be observed, by the object's short name.
UNOBSERVED = {
    entry["key"]: entry["unobserved"] for entry in DECLARED.values() if entry["unobserved"]
}


def answers(path=None) -> dict:
    """The captured answers: the attribute names each one carried."""
    captured = json.loads(Path(path or _capture()).read_text(encoding="utf-8"))["objects"]
    # A name ending "[]" records what a list held, beside the name of the list
    # itself. It is not a name the server sent, so no check is shown it.
    found = {}
    for answer, names in captured.items():
        found[answer] = [name for name in names if not name.endswith("[]")]
    return found


def never_sent(elements: dict, declared: dict = DECLARED) -> dict:
    """Declared attributes that no captured answer carries and no reason excuses."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        missing = sorted(set(entry["fields"]) - seen - set(entry["unobserved"]))
        if missing:
            found[fqn] = missing
    return found


def never_read(elements: dict, rows: dict = ROWS, declared: dict = DECLARED) -> dict:
    """Attributes a row reads that an answer it is built from never carries."""
    found = {}
    for key, row in rows.items():
        excused = set(declared[row["of"]]["unobserved"])
        for name in row["capture"]:
            missing = sorted(set(row["reads"]) - set(elements.get(name, ())) - excused)
            if missing:
                found[f"{key} row, from {name}"] = missing
        for fqn, reads in row["also"].items():
            excused = set(declared[fqn]["unobserved"])
            for name in declared[fqn]["capture"]:
                missing = sorted(set(reads) - set(elements.get(name, ())) - excused)
                if missing:
                    found[f"{key} row, {fqn} from {name}"] = missing
    return found


def undeclared(elements: dict, declared: dict = DECLARED) -> dict:
    """What the server sends and the model does not declare. Reported, never a failure."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        found[fqn] = sorted(seen - set(entry["fields"]))
    return found


def outlived(elements: dict, declared: dict = DECLARED) -> dict:
    """Reasons kept for an attribute a captured answer does carry. Reported only."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        stale = sorted(set(entry["unobserved"]) & seen)
        if stale:
            found[fqn] = stale
    return found


def report(elements: dict) -> str:
    """Both directions, in words: the one that fails and the one that only informs."""
    lines = []
    for fqn, extra in undeclared(elements).items():
        entry = DECLARED[fqn]
        lines.append(
            f"{fqn}: declares {len(entry['fields'])} attributes, "
            f"{len(entry['unobserved'])} of them with a reason they were not observed; "
            f"the captured server sends {len(extra)} more, which are not declared"
        )
        if extra:
            lines.append("  not declared: " + ", ".join(extra))
    for fqn, stale in outlived(elements).items():
        lines.append(f"{fqn}: a reason is kept for {stale}, which the capture now carries")
    failures = {**never_sent(elements), **never_read(elements)}
    for where, missing in failures.items():
        lines.append(f"FAIL {where}: {missing} is in no captured answer and has no reason")
    lines.append("capture check: " + ("FAILED" if failures else "passed"))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    captured = answers()
    sys.stdout.write(report(captured))
    sys.exit(1 if never_sent(captured) or never_read(captured) or outlived(captured) else 0)
