# @generated by metaobjects (metagen:elements) from the model in metaobjects/.
# Do not edit: change the metadata and regenerate. A hand edit fails
# `metaobjects verify --codegen`.
"""Builders for the answers a test double gives in place of the real server.

One function per declared object. Each takes the keys of one object by the
server's own names and hands them back in the order given, having refused a
name the model does not declare and the absence of one a real object always
carries. A double that builds every answer through these cannot invent a name.
"""

from __future__ import annotations

ELEMENT = {
    "state": "State",
    "state_attributes": "attributes",
    "context": "context",
    "api_root": "API root",
    "config": "config",
    "rest_error": "error",
    "logbook_entry": "logbook row",
    "statistic_meta": "statistic metadata",
    "statistics_row": "statistics row",
    "history_state": "history row",
    "entity_entry": "entity registry entry",
    "device_entry": "device registry entry",
    "area_entry": "area registry entry",
    "floor_entry": "floor registry entry",
    "entity_update_result": "entity update result",
    "service_domain": "service domain",
    "service": "service",
    "service_field": "service field",
    "service_field_filter": "field filter",
    "selector": "selector",
    "select_selector": "select selector",
    "service_response": "service response",
    "service_target": "service target",
    "service_target_entity": "target entity filter",
    "service_call_result": "service call result",
    "auth_required": "auth_required frame",
    "auth_ok": "auth_ok frame",
    "auth_invalid": "auth_invalid frame",
    "result_message": "result frame",
    "error_message": "error frame",
    "error_detail": "error",
}

ATTRIBUTES = {
    "state": (
        "entity_id",
        "state",
        "attributes",
        "last_changed",
        "last_reported",
        "last_updated",
        "context",
    ),
    "state_attributes": (
        "friendly_name",
        "device_class",
        "state_class",
        "unit_of_measurement",
        "supported_features",
        "brightness",
        "temperature",
        "battery_level",
    ),
    "context": (
        "id",
        "parent_id",
        "user_id",
    ),
    "api_root": ("message",),
    "config": (
        "version",
        "location_name",
    ),
    "rest_error": ("message",),
    "logbook_entry": (
        "when",
        "name",
        "entity_id",
        "domain",
        "state",
        "message",
        "source",
        "context_id",
        "context_user_id",
        "context_event_type",
        "context_domain",
        "context_service",
        "context_entity_id",
        "context_entity_id_name",
        "context_name",
        "context_message",
        "context_source",
    ),
    "statistic_meta": (
        "statistic_id",
        "name",
        "source",
        "has_sum",
        "has_mean",
        "mean_type",
        "display_unit_of_measurement",
        "statistics_unit_of_measurement",
        "unit_class",
    ),
    "statistics_row": (
        "start",
        "end",
        "change",
        "state",
        "sum",
        "mean",
        "min",
        "max",
        "last_reset",
    ),
    "history_state": (
        "state",
        "last_changed",
        "entity_id",
        "attributes",
        "last_updated",
    ),
    "entity_entry": (
        "entity_id",
        "id",
        "unique_id",
        "platform",
        "name",
        "original_name",
        "has_entity_name",
        "area_id",
        "device_id",
        "disabled_by",
        "hidden_by",
        "entity_category",
        "icon",
        "translation_key",
        "config_entry_id",
        "config_subentry_id",
        "categories",
        "options",
        "labels",
        "created_at",
        "modified_at",
        "aliases",
        "capabilities",
        "device_class",
        "original_device_class",
        "original_icon",
    ),
    "device_entry": (
        "id",
        "name",
        "name_by_user",
        "area_id",
        "manufacturer",
        "model",
        "disabled_by",
        "labels",
    ),
    "area_entry": (
        "area_id",
        "name",
        "aliases",
        "floor_id",
        "icon",
    ),
    "floor_entry": (
        "floor_id",
        "name",
        "aliases",
        "icon",
        "level",
        "created_at",
        "modified_at",
    ),
    "entity_update_result": (
        "entity_entry",
        "reload_delay",
    ),
    "service_domain": (
        "domain",
        "services",
    ),
    "service": (
        "name",
        "description",
        "fields",
        "target",
        "response",
    ),
    "service_field": (
        "description",
        "required",
        "example",
        "selector",
        "filter",
        "fields",
        "collapsed",
    ),
    "service_field_filter": ("supported_features",),
    "selector": (
        "select",
        "datetime",
        "number",
        "text",
    ),
    "select_selector": ("options",),
    "service_response": ("optional",),
    "service_target": (
        "entity",
        "device",
    ),
    "service_target_entity": (
        "domain",
        "supported_features",
    ),
    "service_call_result": (
        "changed_states",
        "service_response",
    ),
    "auth_required": (
        "type",
        "ha_version",
    ),
    "auth_ok": (
        "type",
        "ha_version",
    ),
    "auth_invalid": (
        "type",
        "message",
    ),
    "result_message": (
        "id",
        "type",
        "success",
        "result",
    ),
    "error_message": (
        "id",
        "type",
        "success",
        "error",
    ),
    "error_detail": (
        "code",
        "message",
    ),
}

REQUIRED = {
    "state": (
        "entity_id",
        "state",
        "attributes",
        "last_changed",
        "last_reported",
        "last_updated",
    ),
    "state_attributes": (),
    "context": ("id",),
    "api_root": ("message",),
    "config": ("version",),
    "rest_error": ("message",),
    "logbook_entry": ("when",),
    "statistic_meta": (
        "statistic_id",
        "source",
        "has_sum",
    ),
    "statistics_row": (
        "start",
        "end",
    ),
    "history_state": (
        "state",
        "last_changed",
    ),
    "entity_entry": (
        "entity_id",
        "id",
        "unique_id",
        "platform",
    ),
    "device_entry": ("id",),
    "area_entry": (
        "area_id",
        "name",
    ),
    "floor_entry": (
        "floor_id",
        "name",
    ),
    "entity_update_result": ("entity_entry",),
    "service_domain": (
        "domain",
        "services",
    ),
    "service": (),
    "service_field": (),
    "service_field_filter": (),
    "selector": (),
    "select_selector": (),
    "service_response": ("optional",),
    "service_target": (),
    "service_target_entity": (),
    "service_call_result": ("changed_states",),
    "auth_required": (
        "type",
        "ha_version",
    ),
    "auth_ok": (
        "type",
        "ha_version",
    ),
    "auth_invalid": (
        "type",
        "message",
    ),
    "result_message": (
        "id",
        "type",
        "success",
    ),
    "error_message": (
        "id",
        "type",
        "success",
        "error",
    ),
    "error_detail": (
        "code",
        "message",
    ),
}


def _object(kind: str, keys: dict) -> dict:
    unknown = sorted(set(keys) - set(ATTRIBUTES[kind]))
    if unknown:
        raise KeyError(
            f"{kind}: {unknown} is not a key the model declares, and a double may "
            "not invent one; declare it, and the capture check will say whether a real "
            "server sends it"
        )
    absent = [name for name in REQUIRED[kind] if keys.get(name) in (None, "")]
    if absent:
        raise KeyError(f"{kind}: a real {ELEMENT[kind]} object always carries {absent}")
    return keys


def state(**keys) -> dict:
    """The keys of one State object, as homeassistant::core::State declares them."""
    return _object("state", keys)


def state_attributes(**keys) -> dict:
    """The keys of one attributes object, as homeassistant::core::StateAttributes declares them."""
    return _object("state_attributes", keys)


def context(**keys) -> dict:
    """The keys of one context object, as homeassistant::core::Context declares them."""
    return _object("context", keys)


def api_root(**keys) -> dict:
    """The keys of one API root object, as homeassistant::core::ApiRoot declares them."""
    return _object("api_root", keys)


def config(**keys) -> dict:
    """The keys of one config object, as homeassistant::core::Config declares them."""
    return _object("config", keys)


def rest_error(**keys) -> dict:
    """The keys of one error object, as homeassistant::core::RestError declares them."""
    return _object("rest_error", keys)


def logbook_entry(**keys) -> dict:
    """The keys of one logbook row object, as homeassistant::logbook::LogbookEntry declares them."""
    return _object("logbook_entry", keys)


def statistic_meta(**keys) -> dict:
    """The keys of one statistic metadata object, as homeassistant::recorder::StatisticMeta declares them."""
    return _object("statistic_meta", keys)


def statistics_row(**keys) -> dict:
    """The keys of one statistics row object, as homeassistant::recorder::StatisticsRow declares them."""
    return _object("statistics_row", keys)


def history_state(**keys) -> dict:
    """The keys of one history row object, as homeassistant::recorder::HistoryState declares them."""
    return _object("history_state", keys)


def entity_entry(**keys) -> dict:
    """The keys of one entity registry entry object, as homeassistant::registry::EntityEntry declares them."""
    return _object("entity_entry", keys)


def device_entry(**keys) -> dict:
    """The keys of one device registry entry object, as homeassistant::registry::DeviceEntry declares them."""
    return _object("device_entry", keys)


def area_entry(**keys) -> dict:
    """The keys of one area registry entry object, as homeassistant::registry::AreaEntry declares them."""
    return _object("area_entry", keys)


def floor_entry(**keys) -> dict:
    """The keys of one floor registry entry object, as homeassistant::registry::FloorEntry declares them."""
    return _object("floor_entry", keys)


def entity_update_result(**keys) -> dict:
    """The keys of one entity update result object, as homeassistant::registry::EntityUpdateResult declares them."""
    return _object("entity_update_result", keys)


def service_domain(**keys) -> dict:
    """The keys of one service domain object, as homeassistant::services::ServiceDomain declares them."""
    return _object("service_domain", keys)


def service(**keys) -> dict:
    """The keys of one service object, as homeassistant::services::Service declares them."""
    return _object("service", keys)


def service_field(**keys) -> dict:
    """The keys of one service field object, as homeassistant::services::ServiceField declares them."""
    return _object("service_field", keys)


def service_field_filter(**keys) -> dict:
    """The keys of one field filter object, as homeassistant::services::ServiceFieldFilter declares them."""
    return _object("service_field_filter", keys)


def selector(**keys) -> dict:
    """The keys of one selector object, as homeassistant::services::Selector declares them."""
    return _object("selector", keys)


def select_selector(**keys) -> dict:
    """The keys of one select selector object, as homeassistant::services::SelectSelector declares them."""
    return _object("select_selector", keys)


def service_response(**keys) -> dict:
    """The keys of one service response object, as homeassistant::services::ServiceResponse declares them."""
    return _object("service_response", keys)


def service_target(**keys) -> dict:
    """The keys of one service target object, as homeassistant::services::ServiceTarget declares them."""
    return _object("service_target", keys)


def service_target_entity(**keys) -> dict:
    """The keys of one target entity filter object, as homeassistant::services::ServiceTargetEntity declares them."""
    return _object("service_target_entity", keys)


def service_call_result(**keys) -> dict:
    """The keys of one service call result object, as homeassistant::services::ServiceCallResult declares them."""
    return _object("service_call_result", keys)


def auth_required(**keys) -> dict:
    """The keys of one auth_required frame object, as homeassistant::websocket::AuthRequired declares them."""
    return _object("auth_required", keys)


def auth_ok(**keys) -> dict:
    """The keys of one auth_ok frame object, as homeassistant::websocket::AuthOk declares them."""
    return _object("auth_ok", keys)


def auth_invalid(**keys) -> dict:
    """The keys of one auth_invalid frame object, as homeassistant::websocket::AuthInvalid declares them."""
    return _object("auth_invalid", keys)


def result_message(**keys) -> dict:
    """The keys of one result frame object, as homeassistant::websocket::ResultMessage declares them."""
    return _object("result_message", keys)


def error_message(**keys) -> dict:
    """The keys of one error frame object, as homeassistant::websocket::ErrorMessage declares them."""
    return _object("error_message", keys)


def error_detail(**keys) -> dict:
    """The keys of one error object, as homeassistant::websocket::ErrorDetail declares them."""
    return _object("error_detail", keys)
