# @generated by metaobjects (metagen:elements) from the model in metaobjects/.
# Do not edit: change the metadata and regenerate. A hand edit fails
# `metaobjects verify --codegen`.
"""Builders for the answers a test double gives in place of the real server.

One function per declared object. Each takes the attributes of one element by
the server's own names and hands them back in the order given, having refused
a name the model does not declare and the absence of one a real element always
carries. A double that builds every answer through these cannot invent a name.
"""

from __future__ import annotations

ELEMENT = {
    "state": "State",
    "state_attributes": "attributes",
    "context": "context",
    "api_root": "API root",
    "config": "config",
    "rest_error": "error",
    "logbook_entry": "logbook row",
    "statistic_meta": "statistic metadata",
    "statistics_row": "statistics row",
    "history_state": "history row",
    "entity_entry": "entity registry entry",
    "device_entry": "device registry entry",
    "area_entry": "area registry entry",
    "floor_entry": "floor registry entry",
    "entity_update_result": "entity update result",
    "service_domain": "service domain",
    "service": "service",
    "service_field": "service field",
    "service_field_filter": "field filter",
    "selector": "selector",
    "select_selector": "select selector",
    "service_response": "service response",
    "service_target": "service target",
    "service_target_entity": "target entity filter",
    "service_call_result": "service call result",
    "auth_required": "auth_required frame",
    "auth_ok": "auth_ok frame",
    "auth_invalid": "auth_invalid frame",
    "result_message": "result frame",
    "error_message": "error frame",
    "error_detail": "error",
}

ATTRIBUTES = {
    "state": (
        "entity_id",
        "state",
        "attributes",
        "last_changed",
        "last_reported",
        "last_updated",
        "context",
    ),
    "state_attributes": (
        "friendly_name",
        "device_class",
        "state_class",
        "unit_of_measurement",
        "supported_features",
        "brightness",
        "temperature",
        "battery_level",
    ),
    "context": (
        "id",
        "parent_id",
        "user_id",
    ),
    "api_root": ("message",),
    "config": (
        "version",
        "location_name",
    ),
    "rest_error": ("message",),
    "logbook_entry": (
        "when",
        "name",
        "entity_id",
        "domain",
        "state",
        "message",
        "source",
        "context_id",
        "context_user_id",
        "context_event_type",
        "context_domain",
        "context_service",
        "context_entity_id",
        "context_entity_id_name",
        "context_name",
        "context_message",
        "context_source",
    ),
    "statistic_meta": (
        "statistic_id",
        "name",
        "source",
        "has_sum",
        "has_mean",
        "mean_type",
        "display_unit_of_measurement",
        "statistics_unit_of_measurement",
        "unit_class",
    ),
    "statistics_row": (
        "start",
        "end",
        "change",
        "state",
        "sum",
        "mean",
        "min",
        "max",
        "last_reset",
    ),
    "history_state": (
        "state",
        "last_changed",
        "entity_id",
        "attributes",
        "last_updated",
    ),
    "entity_entry": (
        "entity_id",
        "id",
        "unique_id",
        "platform",
        "name",
        "original_name",
        "has_entity_name",
        "area_id",
        "device_id",
        "disabled_by",
        "hidden_by",
        "entity_category",
        "icon",
        "translation_key",
        "config_entry_id",
        "config_subentry_id",
        "categories",
        "options",
        "labels",
        "created_at",
        "modified_at",
        "aliases",
        "capabilities",
        "device_class",
        "original_device_class",
        "original_icon",
    ),
    "device_entry": (
        "id",
        "name",
        "name_by_user",
        "area_id",
        "manufacturer",
        "model",
        "disabled_by",
        "labels",
    ),
    "area_entry": (
        "area_id",
        "name",
        "aliases",
        "floor_id",
        "icon",
    ),
    "floor_entry": (
        "floor_id",
        "name",
        "aliases",
        "icon",
        "level",
        "created_at",
        "modified_at",
    ),
    "entity_update_result": (
        "entity_entry",
        "reload_delay",
    ),
    "service_domain": (
        "domain",
        "services",
    ),
    "service": (
        "name",
        "description",
        "fields",
        "target",
        "response",
    ),
    "service_field": (
        "description",
        "required",
        "example",
        "selector",
        "filter",
        "fields",
        "collapsed",
    ),
    "service_field_filter": ("supported_features",),
    "selector": (
        "select",
        "datetime",
        "number",
        "text",
    ),
    "select_selector": ("options",),
    "service_response": ("optional",),
    "service_target": (
        "entity",
        "device",
    ),
    "service_target_entity": (
        "domain",
        "supported_features",
    ),
    "service_call_result": (
        "changed_states",
        "service_response",
    ),
    "auth_required": (
        "type",
        "ha_version",
    ),
    "auth_ok": (
        "type",
        "ha_version",
    ),
    "auth_invalid": (
        "type",
        "message",
    ),
    "result_message": (
        "id",
        "type",
        "success",
        "result",
    ),
    "error_message": (
        "id",
        "type",
        "success",
        "error",
    ),
    "error_detail": (
        "code",
        "message",
    ),
}

REQUIRED = {
    "state": (
        "entity_id",
        "state",
        "attributes",
        "last_changed",
        "last_reported",
        "last_updated",
    ),
    "state_attributes": (),
    "context": ("id",),
    "api_root": ("message",),
    "config": ("version",),
    "rest_error": ("message",),
    "logbook_entry": ("when",),
    "statistic_meta": (
        "statistic_id",
        "source",
        "has_sum",
    ),
    "statistics_row": (
        "start",
        "end",
    ),
    "history_state": (
        "state",
        "last_changed",
    ),
    "entity_entry": (
        "entity_id",
        "id",
        "unique_id",
        "platform",
    ),
    "device_entry": ("id",),
    "area_entry": (
        "area_id",
        "name",
    ),
    "floor_entry": (
        "floor_id",
        "name",
    ),
    "entity_update_result": ("entity_entry",),
    "service_domain": (
        "domain",
        "services",
    ),
    "service": (),
    "service_field": (),
    "service_field_filter": (),
    "selector": (),
    "select_selector": (),
    "service_response": ("optional",),
    "service_target": (),
    "service_target_entity": (),
    "service_call_result": ("changed_states",),
    "auth_required": (
        "type",
        "ha_version",
    ),
    "auth_ok": (
        "type",
        "ha_version",
    ),
    "auth_invalid": (
        "type",
        "message",
    ),
    "result_message": (
        "id",
        "type",
        "success",
    ),
    "error_message": (
        "id",
        "type",
        "success",
        "error",
    ),
    "error_detail": (
        "code",
        "message",
    ),
}


def _element(kind: str, attributes: dict) -> dict:
    unknown = sorted(set(attributes) - set(ATTRIBUTES[kind]))
    if unknown:
        raise KeyError(
            f"{kind}: {unknown} is not an attribute the model declares, and a double may "
            "not invent one; declare it, and the capture check will say whether a real "
            "server sends it"
        )
    absent = [name for name in REQUIRED[kind] if attributes.get(name) in (None, "")]
    if absent:
        raise KeyError(f"{kind}: a real {ELEMENT[kind]} element always carries {absent}")
    return attributes


def state(**attributes) -> dict:
    """The attributes of one State element, as homeassistant::core::State declares them."""
    return _element("state", attributes)


def state_attributes(**attributes) -> dict:
    """The attributes of one attributes element, as homeassistant::core::StateAttributes declares them."""
    return _element("state_attributes", attributes)


def context(**attributes) -> dict:
    """The attributes of one context element, as homeassistant::core::Context declares them."""
    return _element("context", attributes)


def api_root(**attributes) -> dict:
    """The attributes of one API root element, as homeassistant::core::ApiRoot declares them."""
    return _element("api_root", attributes)


def config(**attributes) -> dict:
    """The attributes of one config element, as homeassistant::core::Config declares them."""
    return _element("config", attributes)


def rest_error(**attributes) -> dict:
    """The attributes of one error element, as homeassistant::core::RestError declares them."""
    return _element("rest_error", attributes)


def logbook_entry(**attributes) -> dict:
    """The attributes of one logbook row element, as homeassistant::logbook::LogbookEntry declares them."""
    return _element("logbook_entry", attributes)


def statistic_meta(**attributes) -> dict:
    """The attributes of one statistic metadata element, as homeassistant::recorder::StatisticMeta declares them."""
    return _element("statistic_meta", attributes)


def statistics_row(**attributes) -> dict:
    """The attributes of one statistics row element, as homeassistant::recorder::StatisticsRow declares them."""
    return _element("statistics_row", attributes)


def history_state(**attributes) -> dict:
    """The attributes of one history row element, as homeassistant::recorder::HistoryState declares them."""
    return _element("history_state", attributes)


def entity_entry(**attributes) -> dict:
    """The attributes of one entity registry entry element, as homeassistant::registry::EntityEntry declares them."""
    return _element("entity_entry", attributes)


def device_entry(**attributes) -> dict:
    """The attributes of one device registry entry element, as homeassistant::registry::DeviceEntry declares them."""
    return _element("device_entry", attributes)


def area_entry(**attributes) -> dict:
    """The attributes of one area registry entry element, as homeassistant::registry::AreaEntry declares them."""
    return _element("area_entry", attributes)


def floor_entry(**attributes) -> dict:
    """The attributes of one floor registry entry element, as homeassistant::registry::FloorEntry declares them."""
    return _element("floor_entry", attributes)


def entity_update_result(**attributes) -> dict:
    """The attributes of one entity update result element, as homeassistant::registry::EntityUpdateResult declares them."""
    return _element("entity_update_result", attributes)


def service_domain(**attributes) -> dict:
    """The attributes of one service domain element, as homeassistant::services::ServiceDomain declares them."""
    return _element("service_domain", attributes)


def service(**attributes) -> dict:
    """The attributes of one service element, as homeassistant::services::Service declares them."""
    return _element("service", attributes)


def service_field(**attributes) -> dict:
    """The attributes of one service field element, as homeassistant::services::ServiceField declares them."""
    return _element("service_field", attributes)


def service_field_filter(**attributes) -> dict:
    """The attributes of one field filter element, as homeassistant::services::ServiceFieldFilter declares them."""
    return _element("service_field_filter", attributes)


def selector(**attributes) -> dict:
    """The attributes of one selector element, as homeassistant::services::Selector declares them."""
    return _element("selector", attributes)


def select_selector(**attributes) -> dict:
    """The attributes of one select selector element, as homeassistant::services::SelectSelector declares them."""
    return _element("select_selector", attributes)


def service_response(**attributes) -> dict:
    """The attributes of one service response element, as homeassistant::services::ServiceResponse declares them."""
    return _element("service_response", attributes)


def service_target(**attributes) -> dict:
    """The attributes of one service target element, as homeassistant::services::ServiceTarget declares them."""
    return _element("service_target", attributes)


def service_target_entity(**attributes) -> dict:
    """The attributes of one target entity filter element, as homeassistant::services::ServiceTargetEntity declares them."""
    return _element("service_target_entity", attributes)


def service_call_result(**attributes) -> dict:
    """The attributes of one service call result element, as homeassistant::services::ServiceCallResult declares them."""
    return _element("service_call_result", attributes)


def auth_required(**attributes) -> dict:
    """The attributes of one auth_required frame element, as homeassistant::websocket::AuthRequired declares them."""
    return _element("auth_required", attributes)


def auth_ok(**attributes) -> dict:
    """The attributes of one auth_ok frame element, as homeassistant::websocket::AuthOk declares them."""
    return _element("auth_ok", attributes)


def auth_invalid(**attributes) -> dict:
    """The attributes of one auth_invalid frame element, as homeassistant::websocket::AuthInvalid declares them."""
    return _element("auth_invalid", attributes)


def result_message(**attributes) -> dict:
    """The attributes of one result frame element, as homeassistant::websocket::ResultMessage declares them."""
    return _element("result_message", attributes)


def error_message(**attributes) -> dict:
    """The attributes of one error frame element, as homeassistant::websocket::ErrorMessage declares them."""
    return _element("error_message", attributes)


def error_detail(**attributes) -> dict:
    """The attributes of one error element, as homeassistant::websocket::ErrorDetail declares them."""
    return _element("error_detail", attributes)
