# @generated by metaobjects (metagen:readers) from the model in metaobjects/.
# Do not edit: change the metadata and regenerate. A hand edit fails
# `metaobjects verify --codegen`.
"""Readers for what the server answers: one frozen class per declared object.

``read(raw)`` takes one answer as it was parsed and gives each name the model
declares of it as an attribute. A name the answer did not carry reads as
``None``, and so does one it carried as null: ``sent(name)`` tells the two
apart. Nothing is invented and nothing is lost: the answer itself is kept as
``raw``, untouched, with every name the model does not declare still in it.
``missing()`` is the names a real answer always carries that this one did not.

A name that holds another declared object is read through that object's reader:
one as that reader, a list of them as a tuple and a map of them as a dict. What
is there and is not an object is left out, and is still in ``raw``.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field


def _answer(reader: str, raw) -> Mapping:
    """One answer, refused when it is not the mapping one is parsed into."""
    if not isinstance(raw, Mapping):
        got = type(raw).__name__
        raise TypeError(f"{reader}.read takes a mapping, not {got}")
    return raw


def _items(value):
    """What a list held, as a tuple, or ``None`` for what is not a list."""
    return tuple(value) if isinstance(value, (list, tuple)) else None


def _one(reader, value):
    """A nested object through its own reader, or ``None`` for no object."""
    return reader.read(value) if isinstance(value, Mapping) else None


def _many(reader, value):
    """A list of nested objects, each through its reader, or ``None``."""
    if not isinstance(value, (list, tuple)):
        return None
    objects = (item for item in value if isinstance(item, Mapping))
    return tuple(reader.read(item) for item in objects)


def _keyed(reader, value):
    """A map of nested objects, each through its reader, or ``None``."""
    if not isinstance(value, Mapping):
        return None
    found = {}
    for key, item in value.items():
        if isinstance(item, Mapping):
            found[key] = reader.read(item)
    return found


@dataclass(frozen=True)
class State:
    """One State object, as homeassistant::core::State declares it."""

    entity_id: str | None = None
    state: str | None = None
    attributes: StateAttributes | None = None
    last_changed: str | None = None
    last_reported: str | None = None
    last_updated: str | None = None
    context: Context | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> State:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("State", raw)
        return cls(
            entity_id=raw.get("entity_id"),
            state=raw.get("state"),
            attributes=_one(StateAttributes, raw.get("attributes")),
            last_changed=raw.get("last_changed"),
            last_reported=raw.get("last_reported"),
            last_updated=raw.get("last_updated"),
            context=_one(Context, raw.get("context")),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real State object always carries and this lacks."""
        carried = {
            "entity_id": self.entity_id,
            "state": self.state,
            "attributes": self.attributes,
            "last_changed": self.last_changed,
            "last_reported": self.last_reported,
            "last_updated": self.last_updated,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class StateAttributes:
    """One attributes object, as homeassistant::core::StateAttributes declares it."""

    friendly_name: str | None = None
    device_class: str | None = None
    state_class: str | None = None
    unit_of_measurement: str | None = None
    supported_features: int | None = None
    brightness: int | None = None
    temperature: float | None = None
    battery_level: int | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> StateAttributes:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("StateAttributes", raw)
        return cls(
            friendly_name=raw.get("friendly_name"),
            device_class=raw.get("device_class"),
            state_class=raw.get("state_class"),
            unit_of_measurement=raw.get("unit_of_measurement"),
            supported_features=raw.get("supported_features"),
            brightness=raw.get("brightness"),
            temperature=raw.get("temperature"),
            battery_level=raw.get("battery_level"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real attributes object always carries and this lacks."""
        return ()


@dataclass(frozen=True)
class Context:
    """One context object, as homeassistant::core::Context declares it."""

    id: str | None = None
    parent_id: str | None = None
    user_id: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> Context:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("Context", raw)
        return cls(
            id=raw.get("id"),
            parent_id=raw.get("parent_id"),
            user_id=raw.get("user_id"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real context object always carries and this lacks."""
        carried = {
            "id": self.id,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class ApiRoot:
    """One API root object, as homeassistant::core::ApiRoot declares it."""

    message: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ApiRoot:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ApiRoot", raw)
        return cls(
            message=raw.get("message"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real API root object always carries and this lacks."""
        carried = {
            "message": self.message,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class Config:
    """One config object, as homeassistant::core::Config declares it."""

    version: str | None = None
    location_name: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> Config:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("Config", raw)
        return cls(
            version=raw.get("version"),
            location_name=raw.get("location_name"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real config object always carries and this lacks."""
        carried = {
            "version": self.version,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class RestError:
    """One error object, as homeassistant::core::RestError declares it."""

    message: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> RestError:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("RestError", raw)
        return cls(
            message=raw.get("message"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real error object always carries and this lacks."""
        carried = {
            "message": self.message,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class LogbookEntry:
    """One logbook row object, as homeassistant::logbook::LogbookEntry declares it."""

    when: str | None = None
    name: str | None = None
    entity_id: str | None = None
    domain: str | None = None
    state: str | None = None
    message: str | None = None
    source: str | None = None
    context_id: str | None = None
    context_user_id: str | None = None
    context_event_type: str | None = None
    context_domain: str | None = None
    context_service: str | None = None
    context_entity_id: str | None = None
    context_entity_id_name: str | None = None
    context_name: str | None = None
    context_message: str | None = None
    context_source: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> LogbookEntry:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("LogbookEntry", raw)
        return cls(
            when=raw.get("when"),
            name=raw.get("name"),
            entity_id=raw.get("entity_id"),
            domain=raw.get("domain"),
            state=raw.get("state"),
            message=raw.get("message"),
            source=raw.get("source"),
            context_id=raw.get("context_id"),
            context_user_id=raw.get("context_user_id"),
            context_event_type=raw.get("context_event_type"),
            context_domain=raw.get("context_domain"),
            context_service=raw.get("context_service"),
            context_entity_id=raw.get("context_entity_id"),
            context_entity_id_name=raw.get("context_entity_id_name"),
            context_name=raw.get("context_name"),
            context_message=raw.get("context_message"),
            context_source=raw.get("context_source"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real logbook row object always carries and this lacks."""
        carried = {
            "when": self.when,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class StatisticMeta:
    """One statistic metadata object, as homeassistant::recorder::StatisticMeta declares it."""

    statistic_id: str | None = None
    name: str | None = None
    source: str | None = None
    has_sum: bool | None = None
    has_mean: bool | None = None
    mean_type: int | None = None
    display_unit_of_measurement: str | None = None
    statistics_unit_of_measurement: str | None = None
    unit_class: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> StatisticMeta:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("StatisticMeta", raw)
        return cls(
            statistic_id=raw.get("statistic_id"),
            name=raw.get("name"),
            source=raw.get("source"),
            has_sum=raw.get("has_sum"),
            has_mean=raw.get("has_mean"),
            mean_type=raw.get("mean_type"),
            display_unit_of_measurement=raw.get("display_unit_of_measurement"),
            statistics_unit_of_measurement=raw.get(
                "statistics_unit_of_measurement",
            ),
            unit_class=raw.get("unit_class"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real statistic metadata object always carries and this lacks."""
        carried = {
            "statistic_id": self.statistic_id,
            "source": self.source,
            "has_sum": self.has_sum,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class StatisticsRow:
    """One statistics row object, as homeassistant::recorder::StatisticsRow declares it."""

    start: int | None = None
    end: int | None = None
    change: float | None = None
    state: float | None = None
    sum: float | None = None
    mean: float | None = None
    min: float | None = None
    max: float | None = None
    last_reset: float | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> StatisticsRow:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("StatisticsRow", raw)
        return cls(
            start=raw.get("start"),
            end=raw.get("end"),
            change=raw.get("change"),
            state=raw.get("state"),
            sum=raw.get("sum"),
            mean=raw.get("mean"),
            min=raw.get("min"),
            max=raw.get("max"),
            last_reset=raw.get("last_reset"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real statistics row object always carries and this lacks."""
        carried = {
            "start": self.start,
            "end": self.end,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class HistoryState:
    """One history row object, as homeassistant::recorder::HistoryState declares it."""

    state: str | None = None
    last_changed: str | None = None
    entity_id: str | None = None
    attributes: StateAttributes | None = None
    last_updated: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> HistoryState:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("HistoryState", raw)
        return cls(
            state=raw.get("state"),
            last_changed=raw.get("last_changed"),
            entity_id=raw.get("entity_id"),
            attributes=_one(StateAttributes, raw.get("attributes")),
            last_updated=raw.get("last_updated"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real history row object always carries and this lacks."""
        carried = {
            "state": self.state,
            "last_changed": self.last_changed,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class EntityEntry:
    """One entity registry entry object, as homeassistant::registry::EntityEntry declares it."""

    entity_id: str | None = None
    id: str | None = None
    unique_id: str | None = None
    platform: str | None = None
    name: str | None = None
    original_name: str | None = None
    has_entity_name: bool | None = None
    area_id: str | None = None
    device_id: str | None = None
    disabled_by: str | None = None
    hidden_by: str | None = None
    entity_category: str | None = None
    icon: str | None = None
    translation_key: str | None = None
    config_entry_id: str | None = None
    config_subentry_id: str | None = None
    categories: object = None
    options: object = None
    labels: tuple[str, ...] | None = None
    created_at: float | None = None
    modified_at: float | None = None
    aliases: tuple[str, ...] | None = None
    capabilities: object = None
    device_class: str | None = None
    original_device_class: str | None = None
    original_icon: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> EntityEntry:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("EntityEntry", raw)
        return cls(
            entity_id=raw.get("entity_id"),
            id=raw.get("id"),
            unique_id=raw.get("unique_id"),
            platform=raw.get("platform"),
            name=raw.get("name"),
            original_name=raw.get("original_name"),
            has_entity_name=raw.get("has_entity_name"),
            area_id=raw.get("area_id"),
            device_id=raw.get("device_id"),
            disabled_by=raw.get("disabled_by"),
            hidden_by=raw.get("hidden_by"),
            entity_category=raw.get("entity_category"),
            icon=raw.get("icon"),
            translation_key=raw.get("translation_key"),
            config_entry_id=raw.get("config_entry_id"),
            config_subentry_id=raw.get("config_subentry_id"),
            categories=raw.get("categories"),
            options=raw.get("options"),
            labels=_items(raw.get("labels")),
            created_at=raw.get("created_at"),
            modified_at=raw.get("modified_at"),
            aliases=_items(raw.get("aliases")),
            capabilities=raw.get("capabilities"),
            device_class=raw.get("device_class"),
            original_device_class=raw.get("original_device_class"),
            original_icon=raw.get("original_icon"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real entity registry entry object always carries and this lacks."""
        carried = {
            "entity_id": self.entity_id,
            "id": self.id,
            "unique_id": self.unique_id,
            "platform": self.platform,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class DeviceEntry:
    """One device registry entry object, as homeassistant::registry::DeviceEntry declares it."""

    id: str | None = None
    name: str | None = None
    name_by_user: str | None = None
    area_id: str | None = None
    manufacturer: str | None = None
    model: str | None = None
    disabled_by: str | None = None
    labels: tuple[str, ...] | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> DeviceEntry:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("DeviceEntry", raw)
        return cls(
            id=raw.get("id"),
            name=raw.get("name"),
            name_by_user=raw.get("name_by_user"),
            area_id=raw.get("area_id"),
            manufacturer=raw.get("manufacturer"),
            model=raw.get("model"),
            disabled_by=raw.get("disabled_by"),
            labels=_items(raw.get("labels")),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real device registry entry object always carries and this lacks."""
        carried = {
            "id": self.id,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class AreaEntry:
    """One area registry entry object, as homeassistant::registry::AreaEntry declares it."""

    area_id: str | None = None
    name: str | None = None
    aliases: tuple[str, ...] | None = None
    floor_id: str | None = None
    icon: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> AreaEntry:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("AreaEntry", raw)
        return cls(
            area_id=raw.get("area_id"),
            name=raw.get("name"),
            aliases=_items(raw.get("aliases")),
            floor_id=raw.get("floor_id"),
            icon=raw.get("icon"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real area registry entry object always carries and this lacks."""
        carried = {
            "area_id": self.area_id,
            "name": self.name,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class FloorEntry:
    """One floor registry entry object, as homeassistant::registry::FloorEntry declares it."""

    floor_id: str | None = None
    name: str | None = None
    aliases: tuple[str, ...] | None = None
    icon: str | None = None
    level: int | None = None
    created_at: float | None = None
    modified_at: float | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> FloorEntry:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("FloorEntry", raw)
        return cls(
            floor_id=raw.get("floor_id"),
            name=raw.get("name"),
            aliases=_items(raw.get("aliases")),
            icon=raw.get("icon"),
            level=raw.get("level"),
            created_at=raw.get("created_at"),
            modified_at=raw.get("modified_at"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real floor registry entry object always carries and this lacks."""
        carried = {
            "floor_id": self.floor_id,
            "name": self.name,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class EntityUpdateResult:
    """One entity update result object, as homeassistant::registry::EntityUpdateResult declares it."""

    entity_entry: EntityEntry | None = None
    reload_delay: int | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> EntityUpdateResult:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("EntityUpdateResult", raw)
        return cls(
            entity_entry=_one(EntityEntry, raw.get("entity_entry")),
            reload_delay=raw.get("reload_delay"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real entity update result object always carries and this lacks."""
        carried = {
            "entity_entry": self.entity_entry,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class ServiceDomain:
    """One service domain object, as homeassistant::services::ServiceDomain declares it."""

    domain: str | None = None
    services: dict[str, Service] | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ServiceDomain:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ServiceDomain", raw)
        return cls(
            domain=raw.get("domain"),
            services=_keyed(Service, raw.get("services")),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real service domain object always carries and this lacks."""
        carried = {
            "domain": self.domain,
            "services": self.services,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class Service:
    """One service object, as homeassistant::services::Service declares it."""

    name: str | None = None
    description: str | None = None
    fields: dict[str, ServiceField] | None = None
    target: ServiceTarget | None = None
    response: ServiceResponse | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> Service:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("Service", raw)
        return cls(
            name=raw.get("name"),
            description=raw.get("description"),
            fields=_keyed(ServiceField, raw.get("fields")),
            target=_one(ServiceTarget, raw.get("target")),
            response=_one(ServiceResponse, raw.get("response")),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real service object always carries and this lacks."""
        return ()


@dataclass(frozen=True)
class ServiceField:
    """One service field object, as homeassistant::services::ServiceField declares it."""

    description: str | None = None
    required: bool | None = None
    example: object = None
    selector: Selector | None = None
    filter: ServiceFieldFilter | None = None
    fields: dict[str, ServiceField] | None = None
    collapsed: bool | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ServiceField:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ServiceField", raw)
        return cls(
            description=raw.get("description"),
            required=raw.get("required"),
            example=raw.get("example"),
            selector=_one(Selector, raw.get("selector")),
            filter=_one(ServiceFieldFilter, raw.get("filter")),
            fields=_keyed(ServiceField, raw.get("fields")),
            collapsed=raw.get("collapsed"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real service field object always carries and this lacks."""
        return ()


@dataclass(frozen=True)
class ServiceFieldFilter:
    """One field filter object, as homeassistant::services::ServiceFieldFilter declares it."""

    supported_features: tuple[int, ...] | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ServiceFieldFilter:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ServiceFieldFilter", raw)
        return cls(
            supported_features=_items(raw.get("supported_features")),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real field filter object always carries and this lacks."""
        return ()


@dataclass(frozen=True)
class Selector:
    """One selector object, as homeassistant::services::Selector declares it."""

    select: SelectSelector | None = None
    datetime: object = None
    number: object = None
    text: object = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> Selector:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("Selector", raw)
        return cls(
            select=_one(SelectSelector, raw.get("select")),
            datetime=raw.get("datetime"),
            number=raw.get("number"),
            text=raw.get("text"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real selector object always carries and this lacks."""
        return ()


@dataclass(frozen=True)
class SelectSelector:
    """One select selector object, as homeassistant::services::SelectSelector declares it."""

    options: tuple[str, ...] | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> SelectSelector:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("SelectSelector", raw)
        return cls(
            options=_items(raw.get("options")),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real select selector object always carries and this lacks."""
        return ()


@dataclass(frozen=True)
class ServiceResponse:
    """One service response object, as homeassistant::services::ServiceResponse declares it."""

    optional: bool | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ServiceResponse:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ServiceResponse", raw)
        return cls(
            optional=raw.get("optional"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real service response object always carries and this lacks."""
        carried = {
            "optional": self.optional,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class ServiceTarget:
    """One service target object, as homeassistant::services::ServiceTarget declares it."""

    entity: tuple[ServiceTargetEntity, ...] | None = None
    device: object = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ServiceTarget:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ServiceTarget", raw)
        return cls(
            entity=_many(ServiceTargetEntity, raw.get("entity")),
            device=raw.get("device"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real service target object always carries and this lacks."""
        return ()


@dataclass(frozen=True)
class ServiceTargetEntity:
    """One target entity filter object, as homeassistant::services::ServiceTargetEntity declares it."""

    domain: tuple[str, ...] | None = None
    supported_features: tuple[int, ...] | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ServiceTargetEntity:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ServiceTargetEntity", raw)
        return cls(
            domain=_items(raw.get("domain")),
            supported_features=_items(raw.get("supported_features")),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real target entity filter object always carries and this lacks."""
        return ()


@dataclass(frozen=True)
class ServiceCallResult:
    """One service call result object, as homeassistant::services::ServiceCallResult declares it."""

    changed_states: tuple[State, ...] | None = None
    service_response: object = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ServiceCallResult:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ServiceCallResult", raw)
        return cls(
            changed_states=_many(State, raw.get("changed_states")),
            service_response=raw.get("service_response"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real service call result object always carries and this lacks."""
        carried = {
            "changed_states": self.changed_states,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class AuthRequired:
    """One auth_required frame object, as homeassistant::websocket::AuthRequired declares it."""

    type: str | None = None
    ha_version: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> AuthRequired:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("AuthRequired", raw)
        return cls(
            type=raw.get("type"),
            ha_version=raw.get("ha_version"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real auth_required frame object always carries and this lacks."""
        carried = {
            "type": self.type,
            "ha_version": self.ha_version,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class AuthOk:
    """One auth_ok frame object, as homeassistant::websocket::AuthOk declares it."""

    type: str | None = None
    ha_version: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> AuthOk:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("AuthOk", raw)
        return cls(
            type=raw.get("type"),
            ha_version=raw.get("ha_version"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real auth_ok frame object always carries and this lacks."""
        carried = {
            "type": self.type,
            "ha_version": self.ha_version,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class AuthInvalid:
    """One auth_invalid frame object, as homeassistant::websocket::AuthInvalid declares it."""

    type: str | None = None
    message: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> AuthInvalid:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("AuthInvalid", raw)
        return cls(
            type=raw.get("type"),
            message=raw.get("message"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real auth_invalid frame object always carries and this lacks."""
        carried = {
            "type": self.type,
            "message": self.message,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class ResultMessage:
    """One result frame object, as homeassistant::websocket::ResultMessage declares it."""

    id: int | None = None
    type: str | None = None
    success: bool | None = None
    result: object = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ResultMessage:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ResultMessage", raw)
        return cls(
            id=raw.get("id"),
            type=raw.get("type"),
            success=raw.get("success"),
            result=raw.get("result"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real result frame object always carries and this lacks."""
        carried = {
            "id": self.id,
            "type": self.type,
            "success": self.success,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class ErrorMessage:
    """One error frame object, as homeassistant::websocket::ErrorMessage declares it."""

    id: int | None = None
    type: str | None = None
    success: bool | None = None
    error: ErrorDetail | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ErrorMessage:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ErrorMessage", raw)
        return cls(
            id=raw.get("id"),
            type=raw.get("type"),
            success=raw.get("success"),
            error=_one(ErrorDetail, raw.get("error")),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real error frame object always carries and this lacks."""
        carried = {
            "id": self.id,
            "type": self.type,
            "success": self.success,
            "error": self.error,
        }
        return tuple(name for name, value in carried.items() if value is None)


@dataclass(frozen=True)
class ErrorDetail:
    """One error object, as homeassistant::websocket::ErrorDetail declares it."""

    code: str | None = None
    message: str | None = None
    raw: Mapping = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def read(cls, raw) -> ErrorDetail:
        """Read one answer. A key it did not carry is ``None``."""
        raw = _answer("ErrorDetail", raw)
        return cls(
            code=raw.get("code"),
            message=raw.get("message"),
            raw=raw,
        )

    def sent(self, name: str) -> bool:
        """Whether the answer carried this key at all, as null or not."""
        return name in self.raw

    def missing(self) -> tuple:
        """The keys a real error object always carries and this lacks."""
        carried = {
            "code": self.code,
            "message": self.message,
        }
        return tuple(name for name, value in carried.items() if value is None)
