# @generated by metaobjects (metagen:rows) from the model in metaobjects/.
# Do not edit: change the metadata and regenerate. A hand edit fails
# `metaobjects verify --codegen`.
"""The rows this tool prints: the columns each offers, and what each one reads.

``FIELDS`` is every column a row can carry, in the order they are documented and
printed. ``DEFAULT`` is the set shown when no columns are asked for. ``READS`` is
the attributes of the upstream object that each column is read from: nothing at
run time reads it, and it is here so that what a column is made of ships with
the column, for the test suite and for whatever builds on this package.
"""

from __future__ import annotations

FIELDS = {
    "state": (
        "entity_id",
        "name",
        "state",
        "domain",
        "last_changed",
        "last_updated",
        "last_reported",
        "age",
    ),
    "entity": (
        "entity_id",
        "name",
        "area",
        "area_id",
        "platform",
        "domain",
        "device_id",
        "original_name",
        "disabled",
        "hidden",
        "entity_category",
    ),
    "device": (
        "device_id",
        "name",
        "area",
        "area_id",
        "manufacturer",
        "model",
        "entities",
    ),
    "area": (
        "area_id",
        "name",
        "entities",
        "devices",
        "floor_id",
    ),
    "logbook": (
        "when",
        "name",
        "entity_id",
        "event",
        "cause",
        "domain",
        "state",
    ),
    "statistic": (
        "statistic_id",
        "name",
        "kind",
        "unit",
        "source",
        "unit_class",
    ),
    "service_domain": (
        "domain",
        "services",
    ),
}

DEFAULT = {
    "state": (
        "entity_id",
        "name",
        "state",
    ),
    "entity": (
        "entity_id",
        "name",
        "area",
    ),
    "device": (
        "device_id",
        "name",
        "area",
    ),
    "area": (
        "area_id",
        "name",
        "entities",
        "devices",
    ),
    "logbook": (
        "when",
        "name",
        "event",
        "cause",
    ),
    "statistic": (
        "statistic_id",
        "name",
        "kind",
        "unit",
    ),
    "service_domain": (
        "domain",
        "services",
    ),
}

READS = {
    "state": {
        "entity_id": ("entity_id",),
        "name": (
            "attributes",
            "entity_id",
        ),
        "state": ("state",),
        "domain": ("entity_id",),
        "last_changed": ("last_changed",),
        "last_updated": ("last_updated",),
        "last_reported": (
            "last_reported",
            "last_updated",
        ),
        "age": (
            "last_reported",
            "last_updated",
        ),
    },
    "entity": {
        "entity_id": ("entity_id",),
        "name": (
            "name",
            "device_id",
            "original_name",
        ),
        "area": (
            "area_id",
            "device_id",
        ),
        "area_id": (
            "area_id",
            "device_id",
        ),
        "platform": ("platform",),
        "domain": ("entity_id",),
        "device_id": ("device_id",),
        "original_name": ("original_name",),
        "disabled": ("disabled_by",),
        "hidden": ("hidden_by",),
        "entity_category": ("entity_category",),
    },
    "device": {
        "device_id": ("id",),
        "name": (
            "name_by_user",
            "name",
        ),
        "area": ("area_id",),
        "area_id": ("area_id",),
        "manufacturer": ("manufacturer",),
        "model": ("model",),
        "entities": ("id",),
    },
    "area": {
        "area_id": ("area_id",),
        "name": ("name",),
        "entities": ("area_id",),
        "devices": ("area_id",),
        "floor_id": ("floor_id",),
    },
    "logbook": {
        "when": ("when",),
        "name": ("name",),
        "entity_id": ("entity_id",),
        "event": (
            "message",
            "state",
        ),
        "cause": (
            "context_event_type",
            "context_name",
            "context_entity_id_name",
            "context_domain",
            "context_service",
            "context_entity_id",
            "context_user_id",
        ),
        "domain": ("domain",),
        "state": ("state",),
    },
    "statistic": {
        "statistic_id": ("statistic_id",),
        "name": (
            "name",
            "statistic_id",
        ),
        "kind": (
            "has_sum",
            "mean_type",
            "has_mean",
        ),
        "unit": (
            "display_unit_of_measurement",
            "statistics_unit_of_measurement",
        ),
        "source": ("source",),
        "unit_class": ("unit_class",),
    },
    "service_domain": {
        "domain": ("domain",),
        "services": ("services",),
    },
}
